##서버 포트 설정
#server.port=8000
#
##인코딩 UTF-8 설정
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.servlet.encoding.force-request=true
#server.servlet.encoding.force-response=true
#server.tomcat.uri-encoding=UTF-8
#
##뷰리졸버 설정
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp


server:
  port: 8000
   
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springboot_jihun?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: toor
  security:
    user:
      name: test
      password: 1234 
    oauth2:
      client:
        registration:
          google:
            client-id: 534795820541-b7bdrl2kia4419eaaaajf5fisqd9jgc4.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
mybatis:
  mapper-locations:
  - /mappers/*.xml